
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      ./gitpod-init.sh
  - command: |
      ./gitpod-command.sh
ports:
  - port: 3000
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore
  - port: 9601
    onOpen: ignore
  - port: 9602
    onOpen: ignore
vscode:
  extensions:
    - k--kato.intellij-idea-keybindings